// <auto-generated />
using System;
using IPTVGuideDog.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPTVGuideDog.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218202605_AddGuideDogSchema")]
    partial class AddGuideDogSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("IPTVGuideDog.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.CanonicalChannel", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<int>("ChannelNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channel_number");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EventPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_policy");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsEvent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_event");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo_url");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("ChannelId");

                    b.HasIndex("ProfileId", "ChannelNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_canonical_channels_profile_number");

                    b.HasIndex("ProfileId", "Enabled")
                        .HasDatabaseName("idx_canonical_channels_profile_enabled");

                    b.ToTable("canonical_channels", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ChannelMatchRule", b =>
                {
                    b.Property<string>("RuleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<int>("DefaultPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("default_priority");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsEventRule")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_event_rule");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("match_type");

                    b.Property<string>("MatchValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("match_value");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<string>("TargetChannelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_channel_id");

                    b.Property<string>("TargetGroupName")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_group_name");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("RuleId");

                    b.HasIndex("TargetChannelId");

                    b.HasIndex("ProfileId", "Enabled")
                        .HasDatabaseName("idx_match_rules_profile");

                    b.ToTable("channel_match_rules", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ChannelSource", b =>
                {
                    b.Property<string>("ChannelSourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_source_id");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<int>("FailureCountRolling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("failure_count_rolling");

                    b.Property<string>("HealthState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("health_state");

                    b.Property<DateTime?>("LastFailureUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_failure_utc");

                    b.Property<DateTime?>("LastSuccessUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_success_utc");

                    b.Property<string>("OverrideStreamUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("override_stream_url");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("ProviderChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_channel_id");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("ChannelSourceId");

                    b.HasIndex("ProviderChannelId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ChannelId", "Priority")
                        .IsUnique()
                        .HasDatabaseName("idx_channel_sources_channel");

                    b.HasIndex("HealthState", "LastFailureUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_channel_sources_health");

                    b.ToTable("channel_sources", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.EpgChannelMap", b =>
                {
                    b.Property<string>("EpgMapId")
                        .HasColumnType("TEXT")
                        .HasColumnName("epg_map_id");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.Property<string>("XmltvChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("xmltv_channel_id");

                    b.HasKey("EpgMapId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ProfileId", "ChannelId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "XmltvChannelId")
                        .IsUnique()
                        .HasDatabaseName("idx_epg_map_profile");

                    b.ToTable("epg_channel_map", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.FetchRun", b =>
                {
                    b.Property<string>("FetchRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetch_run_id");

                    b.Property<int?>("ChannelCountSeen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channel_count_seen");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_utc");

                    b.Property<int?>("PlaylistBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("playlist_bytes");

                    b.Property<string>("PlaylistEtag")
                        .HasColumnType("TEXT")
                        .HasColumnName("playlist_etag");

                    b.Property<string>("PlaylistLastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("playlist_last_modified");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("XmltvBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("xmltv_bytes");

                    b.Property<string>("XmltvEtag")
                        .HasColumnType("TEXT")
                        .HasColumnName("xmltv_etag");

                    b.Property<string>("XmltvLastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("xmltv_last_modified");

                    b.HasKey("FetchRunId");

                    b.HasIndex("ProviderId", "StartedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_fetch_runs_provider_time");

                    b.HasIndex("Status", "StartedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_fetch_runs_status");

                    b.ToTable("fetch_runs", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.Profile", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("MergeMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("merge_mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OutputName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("output_name");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("ProfileId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ProfileProvider", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<string>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.HasKey("ProfileId", "ProviderId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProfileId", "Priority")
                        .HasDatabaseName("idx_profile_providers_profile");

                    b.ToTable("profile_providers", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.Provider", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("headers_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PlaylistUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playlist_url");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(20)
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<string>("XmltvUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("xmltv_url");

                    b.HasKey("ProviderId");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("idx_providers_enabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ProviderChannel", b =>
                {
                    b.Property<string>("ProviderChannelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_channel_id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("EventEndUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_end_utc");

                    b.Property<DateTime?>("EventStartUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_start_utc");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_utc");

                    b.Property<string>("GroupTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_title");

                    b.Property<bool>("IsEvent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_event");

                    b.Property<string>("LastFetchRunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_fetch_run_id");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo_url");

                    b.Property<string>("ProviderChannelKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_channel_key");

                    b.Property<string>("ProviderGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_group_id");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stream_url");

                    b.Property<string>("TvgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tvg_id");

                    b.Property<string>("TvgName")
                        .HasColumnType("TEXT")
                        .HasColumnName("tvg_name");

                    b.HasKey("ProviderChannelId");

                    b.HasIndex("LastFetchRunId");

                    b.HasIndex("ProviderGroupId");

                    b.HasIndex("ProviderId", "Active")
                        .HasDatabaseName("idx_provider_channels_provider_active");

                    b.HasIndex("ProviderId", "LastSeenUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_provider_channels_seen");

                    b.HasIndex("ProviderId", "ProviderChannelKey")
                        .IsUnique()
                        .HasFilter("provider_channel_key IS NOT NULL");

                    b.HasIndex("ProviderId", "IsEvent", "EventStartUtc")
                        .HasDatabaseName("idx_provider_channels_is_event");

                    b.ToTable("provider_channels", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ProviderGroup", b =>
                {
                    b.Property<string>("ProviderGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_group_id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_utc");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_name");

                    b.HasKey("ProviderGroupId");

                    b.HasIndex("ProviderId", "Active")
                        .HasDatabaseName("idx_provider_groups_provider_active");

                    b.HasIndex("ProviderId", "RawName")
                        .IsUnique();

                    b.ToTable("provider_groups", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.Snapshot", b =>
                {
                    b.Property<string>("SnapshotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("ChannelCountPublished")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channel_count_published");

                    b.Property<string>("ChannelIndexPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_index_path");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_summary");

                    b.Property<string>("PlaylistPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playlist_path");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StatusJsonPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status_json_path");

                    b.Property<string>("XmltvPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("xmltv_path");

                    b.HasKey("SnapshotId");

                    b.HasIndex("ProfileId", "Status", "CreatedUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_snapshots_profile_status");

                    b.ToTable("snapshots", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.StreamKey", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("stream_key");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("LastUsedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_utc");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked");

                    b.HasKey("Value");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("idx_stream_keys_channel");

                    b.HasIndex("ProfileId", "ChannelId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "Revoked")
                        .HasDatabaseName("idx_stream_keys_profile");

                    b.ToTable("stream_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("BLOB");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.CanonicalChannel", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Profile", "Profile")
                        .WithMany("CanonicalChannels")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ChannelMatchRule", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Profile", "Profile")
                        .WithMany("ChannelMatchRules")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPTVGuideDog.Web.Data.Entities.CanonicalChannel", "TargetChannel")
                        .WithMany("TargetingMatchRules")
                        .HasForeignKey("TargetChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");

                    b.Navigation("TargetChannel");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ChannelSource", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.CanonicalChannel", "Channel")
                        .WithMany("ChannelSources")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPTVGuideDog.Web.Data.Entities.ProviderChannel", "ProviderChannel")
                        .WithMany("ChannelSources")
                        .HasForeignKey("ProviderChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Provider", "Provider")
                        .WithMany("ChannelSources")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Provider");

                    b.Navigation("ProviderChannel");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.EpgChannelMap", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.CanonicalChannel", "Channel")
                        .WithMany("EpgChannelMaps")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Profile", "Profile")
                        .WithMany("EpgChannelMaps")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.FetchRun", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Provider", "Provider")
                        .WithMany("FetchRuns")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ProfileProvider", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Profile", "Profile")
                        .WithMany("ProfileProviders")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Provider", "Provider")
                        .WithMany("ProfileProviders")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ProviderChannel", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.FetchRun", "LastFetchRun")
                        .WithMany("ProviderChannels")
                        .HasForeignKey("LastFetchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPTVGuideDog.Web.Data.Entities.ProviderGroup", "ProviderGroup")
                        .WithMany("ProviderChannels")
                        .HasForeignKey("ProviderGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Provider", "Provider")
                        .WithMany("ProviderChannels")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LastFetchRun");

                    b.Navigation("Provider");

                    b.Navigation("ProviderGroup");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ProviderGroup", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Provider", "Provider")
                        .WithMany("ProviderGroups")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.Snapshot", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Profile", "Profile")
                        .WithMany("Snapshots")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.StreamKey", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.Entities.CanonicalChannel", "Channel")
                        .WithMany("StreamKeys")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPTVGuideDog.Web.Data.Entities.Profile", "Profile")
                        .WithMany("StreamKeys")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<uint>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1.ToJson("Data");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPTVGuideDog.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IPTVGuideDog.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.CanonicalChannel", b =>
                {
                    b.Navigation("ChannelSources");

                    b.Navigation("EpgChannelMaps");

                    b.Navigation("StreamKeys");

                    b.Navigation("TargetingMatchRules");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.FetchRun", b =>
                {
                    b.Navigation("ProviderChannels");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.Profile", b =>
                {
                    b.Navigation("CanonicalChannels");

                    b.Navigation("ChannelMatchRules");

                    b.Navigation("EpgChannelMaps");

                    b.Navigation("ProfileProviders");

                    b.Navigation("Snapshots");

                    b.Navigation("StreamKeys");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.Provider", b =>
                {
                    b.Navigation("ChannelSources");

                    b.Navigation("FetchRuns");

                    b.Navigation("ProfileProviders");

                    b.Navigation("ProviderChannels");

                    b.Navigation("ProviderGroups");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ProviderChannel", b =>
                {
                    b.Navigation("ChannelSources");
                });

            modelBuilder.Entity("IPTVGuideDog.Web.Data.Entities.ProviderGroup", b =>
                {
                    b.Navigation("ProviderChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
